name: Deploy My Portfolio to AWS-EC2

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout 
      uses: actions/checkout@v3

    - name: Install rsync and sshpass
      run: sudo apt-get update && sudo apt-get install rsync sshpass

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PASS: ${{ secrets.EC2_PASSWORD }}
      run: |
        # Déploiement du frontend
        sshpass -p "$PASS" rsync -vz --delete --exclude '.git' --exclude '.github' -e "ssh -o StrictHostKeyChecking=no" ./ ${USER}@${HOST}:/var/www/html/nanfacksteve.tech/
        
        # Redémarrage du frontend
        #sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no ${USER}@${HOST} 'docker restart prodcard-frontend-1'
